### ISSUE TITLE
Memory Address to subsystem selection or error -- 24 bits address bus

### ISSUE THREAD

**Issue by sporniket** [sporniket/the-pretender-atari-ste#1]
> WIP

# Expected behavior

_With `address = Signal(24)`, `fc = Signal(3)`,`rxw = Signal(1)` _

**Given** `address`, `fc` and `rxw`

**Then** the corresponding subsystem select signal only is asserted if and only if the access privilege ok

**Then** the error signal is asserted if access privilege is incorrect

# Technical details

### input ports

|Name|Shape|Description|
|---|---|---|
|addr_page|unsigned(4)|The 4 MSB of the 24-bits address|
|addr_sub_page|unsigned(4)|The 4 MSB of the 20 LSB of the 24-bits address|
|addr_sub_sub_page|unsigned(8)|The 8 MSB of the 16 LSB of the 24-bits address|
|addr_long|unsigned(6)|The 6 MSB of the 8 LSB of the 24-bits address|
|fc|unsigned(3)|The function code|
|rxw|unsigned(1)|Direction of the access signal, 0 = Write access, 1 = Read access|

### Output ports
|Name|Shape|Description|
|---|---|---|
|error|unsigned(1)|Asserted when the access to the address is illegal|
|decode|unsigned(??)|one and only one bit is asserted at a given time, unless the access is illegal|

**Decode values**
|Device|bit|
|---|---|
|ROM|0| 
|RAM|1| 
|CART|2| 
|IDE|3| 
|MEMSYSCTL|4| 
|VIDEO|5| 
|TTPAL|6| 
|FDC|7| 
|SCSI|8| 
|PSG|9| 
|DMASOUND_RTC|10| 
|BLITTER|11| 
|DMASCC|12| 
|VMEBUS_CPUCACHE|13| 
|PADDLE|14| 
|VIDEL|15| 
|DSP56K|16| 
|MFP_FPU|17| 
|ACIA_RTC|18| 
 

## User mode (`fc[2] == 0`)

* `error` is asserted if address is out of `$800`—`$CFFFFF`
* otherwise, `decode == RAM` 

See https://freemint.github.io/tos.hyp/en/the_system_vectors.html

> **Bus Error** [...] In user mode this can also happen in attempting to access hardware registers or regions below $800.

## Supervisor mode  (`fc[2] == 1`)

* [x] `addr_page == $0`, 
  * `addr_sub_page == $0`,`addr_sub_sub_page == $0`, `addr_long[1:] == $0` &rArr; ROM, Read only
  * else &rArr; RAM, Read/Write
* [x] `addr_page == $1 to $C` &rArr; RAM, Read/Write
* [ ] `addr_page == $E` &rArr; ROM, Read only
* [ ] `addr_page == $F`, `addr_sub_page == $A` &rArr; ROM Cartridge, Read only
* [ ] `addr_page == $F`, `addr_sub_page == $B` &rArr; ROM Cartridge, Read only 
* [ ] `addr_page == $F`, `addr_sub_page == $F`, `addr_sub_sub_page == $00` &rArr; IDE
* [ ] `addr_page == $F`, `addr_sub_page == $F`, `addr_sub_sub_page == $80` &rArr; Memory/System controller (?) 
* [ ] `addr_page == $F`, `addr_sub_page == $F`, `addr_sub_sub_page == $82` &rArr; Video (shifter/videl)
* [ ] `addr_page == $F`, `addr_sub_page == $F`, `addr_sub_sub_page == $84` &rArr; TT palette
* [ ] `addr_page == $F`, `addr_sub_page == $F`, `addr_sub_sub_page == $85` &rArr; TT palette
* [ ] `addr_page == $F`, `addr_sub_page == $F`, `addr_sub_sub_page == $86` &rArr; WD1772
* [ ] `addr_page == $F`, `addr_sub_page == $F`, `addr_sub_sub_page == $87` &rArr; SCSI
* [ ] `addr_page == $F`, `addr_sub_page == $F`, `addr_sub_sub_page == $88` &rArr; YM-2149
* [ ] `addr_page == $F`, `addr_sub_page == $F`, `addr_sub_sub_page == $89` &rArr; DMA sound, RTC
* [ ] `addr_page == $F`, `addr_sub_page == $F`, `addr_sub_sub_page == $8A` &rArr; Blitter
* [ ] `addr_page == $F`, `addr_sub_page == $F`, `addr_sub_sub_page == $8C` &rArr; DMA SCC (TT)
* [ ] `addr_page == $F`, `addr_sub_page == $F`, `addr_sub_sub_page == $8E` &rArr; VME bus (TT/MSTe), CPU cache control (MSTe) 
* [ ] `addr_page == $F`, `addr_sub_page == $F`, `addr_sub_sub_page == $92` &rArr; Paddle port
* [ ] `addr_page == $F`, `addr_sub_page == $F`, `addr_sub_sub_page == $98` &rArr; Videl palette
* [ ] `addr_page == $F`, `addr_sub_page == $F`, `addr_sub_sub_page == $A2` &rArr; DSP 56k
* [ ] `addr_page == $F`, `addr_sub_page == $F`, `addr_sub_sub_page == $FA` &rArr; MFP 1 & 2, FPU
* [ ] `addr_page == $F`, `addr_sub_page == $F`, `addr_sub_sub_page == $FC` &rArr; ACIA 1 & 2, RTC
* [ ] else &rArr; Illegal

## Subsystem map 

> TODO : expands the $xxFF0xxx area

[reference](https://temlib.org/AtariForumWiki/index.php/Memory_Map_for_Atari_ST,STE,TT_and_Falcon)

Range|R/W|Description
---|---|---
`$0` (Long) |R|SSP at reset, taken from ROM `$xxx` 
`$4` (Long) |R|PC at reset, taken from ROM `$xxx`
`$8`&rarr;`$00CFFFFF`|RW| 14 MB RAM
`$xxD00000`&rarr;`$xxDFFFFF`|?| Unreachable ?
`$xxE00000`&rarr;`$xxEFFFFF`|R| OS ROM (STe onward) ; STE : 256K only, STBook : the full 1MB
`$xxF00000`&rarr;`$xxF0003F`|?| ?
`$xxF00040`&rarr;`$xxF9FFFF`|-| Should be unreachable
`$xxFA0000`&rarr;`$xxFBFFFF`|R| Cartridge ROM
`$xxFC0000`&rarr;`$xxFEFFFF`|R| OS ROM (before STe)
`$xxFF0000`&rarr;`$xxFFFFFF`|RW| Peripheral registers

## Privilege requirements

Only `fc[2]` will be considered.

## Detailed map

> TBD

**Comment by sporniket** [comment]
errors in git comment
